enum ProductType {
  GAMING_PC
  BIKE
  DRONE
}

enum BikeType {
  KIDS
  MOUNTAIN
  ELECTRIC
  BEACH
}

interface Product {
  _id: ID!
  name: String!
  price: Float!
  image: String!
  type: ProductType!
  description: String
  createdBy: Int!
}

type GamingPc implements Product {
  _id: ID!
  name: String!
  price: Float!
  image: String!
  type: ProductType!
  description: String
  liquidCooled: Boolean
  createdBy: Int!
}

type Bike implements Product {
  _id: ID!
  name: String!
  price: Float!
  image: String!
  type: ProductType!
  description: String
  bikeType: BikeType
  createdBy: Int!
}

type Drone implements Product {
  _id: ID!
  name: String!
  price: Float!
  image: String!
  type: ProductType!
  description: String
  range: String
  createdBy: Int!
}

input NewProductInput {
  name: String!
  price: Float!
  image: String!
  type: ProductType!
  description: String
  liquidCooled: Boolean
  bikeType: BikeType
  range: String
  createdBy: Int!
}

input UpdateProductInput {
  name: String
  price: Float
  image: String
  type: ProductType
  description: String
  liquidCooled: Boolean
  bikeType: BikeType
  range: String
  createdBy: Int
}

extend type Query {
  product(id: ID!): Product
  products: [Product]!
}

extend type Mutation {
  newProduct(input: NewProductInput!): Product!
  updateProduct(id: ID!, input: UpdateProductInput!): Product!
  removeProduct(id: ID!): Product
}
